version: '3.4'

services:
  builder:
    build:
      context: .
      target: builder-dev
    volumes:
      - ".:/app"
      - "./node_modules:/app/node_modules"
      - "yarn_cache:/home/user/.cache/yarn"
  devapp:
    build:
      context: .
      target: app-dev
    volumes:
      - ".:/app"
      - "./node_modules:/app/node_modules"
    ports:
      - "3002:3000"
    env_file:
      - ./env/postgres.env
      - ./env/showoff.env
    links:
      - devdb:db
      - testdb
  devdb:
    image: postgres:9.5.7-alpine
    environment:
      - POSTGRES_DB=showoff_db
    env_file:
      - ./env/postgres.env
    volumes:
      - "devdb_data:/var/lib/postgresql/data"
  testdb:
    image: postgres:9.5.7-alpine
    environment:
      - POSTGRES_DB=test_showoff_db
    env_file:
      - ./env/postgres.env

volumes:
  devdb_data:
    external: false
  yarn_cache:
    external: false
