version: '3.4'

services:
  builder:
    build:
      context: .
      target: builder-dev
    volumes:
      - ".:/app"
      - "./node_modules:/app/node_modules"
      - "npm_cache:/home/user/.npm"
  app:
    build:
      context: .
      target: app-dev
    volumes:
      - ".:/app"
      - "./node_modules:/app/node_modules"
    ports:
      - "3001:3000"
    env_file:
      - ./env/postgres.env
    links:
      - db
      - testdb
  db:
    image: postgres:9.5.7-alpine
    environment:
      - POSTGRES_DB=showoff_db
    env_file:
      - ./env/postgres.env
    volumes:
      - "db_data:/var/lib/postgresql/data"
  testdb:
    image: postgres:9.5.7-alpine
    environment:
      - POSTGRES_DB=test_showoff_db
    env_file:
      - ./env/postgres.env

volumes:
  db_data:
    external: false
  npm_cache:
    external: false
