version: '2'

services:
  web:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - ./env/postgres.env
    links:
      - db
  db:
    image: postgres:9.5.7-alpine
    environment:
      - POSTGRES_DB=showoff_db
    env_file:
      - ./env/postgres.env
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:
    external: false
