version: '2'

services:
  web:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./env/postgres.env
    links:
      - db
  db:
    image: postgres:9.6.3-alpine
    environment:
      - POSTGRES_DB=showoff_db
    env_file:
      - ./env/postgres.env
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:
    external: false
