version: '3.2'

services:
  web:
    build: .
    volumes:
      - ".:/app"
      - type: tmpfs
        target: /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./env/postgres.env
    links:
      - db
      - testdb
  db:
    image: postgres:9.5.7-alpine
    environment:
      - POSTGRES_DB=showoff_db
    env_file:
      - ./env/postgres.env
    volumes:
      - "db_data:/var/lib/postgresql/data"
  testdb:
    image: postgres:9.5.7-alpine
    environment:
      - POSTGRES_DB=test_showoff_db
    env_file:
      - ./env/postgres.env

volumes:
  db_data:
    external: false
